spring.application.name=jm-profile-management
spring.datasource.url=jdbc:postgresql://localhost:5432/job_matrix_local
spring.datasource.username=job_matrix
spring.datasource.password=job_matrix
spring.datasource.driver-class-name =org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.maximum-pool-size = 10

#spring.profiles.active=local

# AWS S3 Configuration

aws.region=ap-south-1
aws.s3.bucket-name=jm-profile-management-demo-bucket

# Multipart file configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



spring.profiles.active=local